// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhanKhau.Models;

#nullable disable

namespace QuanLyNhanKhau.Migrations
{
    [DbContext(typeof(QuanLyNhanKhauConText))]
    [Migration("20230103024419_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhanKhau.Models.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccount"));

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nhanKhauId")
                        .HasColumnType("int");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("IdAccount");

                    b.HasIndex("nhanKhauId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.CoSoVatChat", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hienTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<string>("tenCoSoVatChat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdItem");

                    b.ToTable("CoSoVatChat");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.HistoryItem", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<int?>("DoiTuong")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoatDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThayDoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoHoKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdItem");

                    b.HasIndex("DoiTuong");

                    b.ToTable("History");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.HoKhau", b =>
                {
                    b.Property<string>("SoHoKhau")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Duong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phuong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Quan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SoNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoHoKhau");

                    b.ToTable("HoKhau");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.NhanKhau", b =>
                {
                    b.Property<int?>("IdNhanKhau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdNhanKhau"));

                    b.Property<string>("BiDanh")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiTruoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("NgayCapCMND")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayChuyen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDangKi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NguyenNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguyenQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCapCMND")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NoiChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiLamViec")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NoiSinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soHoKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdNhanKhau");

                    b.HasIndex("soHoKhau");

                    b.ToTable("NhanKhau");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.Request", b =>
                {
                    b.Property<int?>("IdRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdRequest"));

                    b.Property<int?>("IdNhanKhau")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ghiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("requestDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("requestTime")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("IdRequest");

                    b.HasIndex("IdNhanKhau");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.Account", b =>
                {
                    b.HasOne("QuanLyNhanKhau.Models.NhanKhau", "nhanKhau")
                        .WithMany()
                        .HasForeignKey("nhanKhauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nhanKhau");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.HistoryItem", b =>
                {
                    b.HasOne("QuanLyNhanKhau.Models.NhanKhau", "DoiTuongO")
                        .WithMany()
                        .HasForeignKey("DoiTuong");

                    b.Navigation("DoiTuongO");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.NhanKhau", b =>
                {
                    b.HasOne("QuanLyNhanKhau.Models.HoKhau", "hoKhau")
                        .WithMany("nhanKhaus")
                        .HasForeignKey("soHoKhau")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("hoKhau");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.Request", b =>
                {
                    b.HasOne("QuanLyNhanKhau.Models.NhanKhau", "nhanKhau")
                        .WithMany()
                        .HasForeignKey("IdNhanKhau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nhanKhau");
                });

            modelBuilder.Entity("QuanLyNhanKhau.Models.HoKhau", b =>
                {
                    b.Navigation("nhanKhaus");
                });
#pragma warning restore 612, 618
        }
    }
}
